-- Deploy asr:role-table to pg
-- requires: set_modified-procedure

BEGIN;

CREATE TABLE role (
    id SERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    description VARCHAR(1024),
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER set_modified BEFORE INSERT OR UPDATE ON role FOR EACH ROW EXECUTE PROCEDURE set_modified();

COMMIT;
